////////////////////////////////////////////////////////////////
// This file is generated by levelgen/main.exe
//

GLOBAL String8 level_names[] = 
{
S8LIT("invalid_level"),
S8LIT("intro"),
S8LIT("intro_red"),
S8LIT("unnamed10"),
S8LIT("unnamed11"),
S8LIT("unnamed12"),
S8LIT("unnamed13"),
S8LIT("unnamed14"),
S8LIT("unnamed15"),
S8LIT("unnamed16"),
S8LIT("unnamed17"),
S8LIT("unnamed18"),
S8LIT("unnamed19"),
S8LIT("unnamed20"),
S8LIT("unnamed21"),
S8LIT("unnamed22"),
S8LIT("unnamed23"),
S8LIT("unnamed24"),
S8LIT("unnamed25"),
S8LIT("unnamed26"),
S8LIT("unnamed27"),
S8LIT("unnamed28"),
S8LIT("unnamed29"),
S8LIT("unnamed3"),
S8LIT("unnamed30"),
S8LIT("unnamed4"),
S8LIT("unnamed5"),
S8LIT("unnamed6"),
S8LIT("unnamed7"),
S8LIT("unnamed8"),
S8LIT("unnamed9"),
};